### ISSUE TITLE
in some cases some building footprints cause crashes when generating the 3D models

### ISSUE THREAD

**Issue by MoritzRoth** [boku-ilen/landscapelab#150]
encountered issue with building id 100
```
C:\landscapelab-dev\landscapelab-server\buildings>blender --background --python create_buildings.py -- 470429
Blender 2.80 (sub 75) (hash f6cb5f54494e built 2019-07-29 09:44 AM)
Read prefs: C:\Users\Projekt Retour\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Start create_buildings.py
Importing other libraries
Setting up directories
Setup done
Connecting to db...
images: {'basement': ['facade_dgrey.jpg', 'plaster_white.jpg'], 'facade': ['normalmap_plaster.jpg', 'plaster_blue.jpg', 'plaster_green.jpg', 'plaster_white.jpg', 'plaster_yellow.jpg'], 'no_rights': [], 'roof': ['roof_2-diffuse.jpg', 'roof_3_diffuse.jpg', 'roof_4_diffuse.jpg'], 'roof_normal': ['roof_2-normal.jpg', 'roof_3-normal.jpg', 'roof_4_normal.jpg']}
imagePath: C:/landscapelab-dev/landscapelab-server/buildings\textures
Connected!
Fetching the next result
SELECT n.name, h.height FROM assetpos_asset as n, (SELECT height FROM buildings_buildingfootprint WHERE id = 470429) as h WHERE n.id IN (SELECT asset_id FROM assetpos_assetpositions WHERE id IN (SELECT asset_id FROM buildings_buildingfootprint WHERE id = 470429));
Creating the model
bounding box data: -13.999044418334961 -19.883710861206055 12.183300018310547 19.59825325012207
bounding box data: -13.999044418334961 -19.883710861206055 12.183300018310547 19.59825325012207
area = 1033.7303833980695
Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 195, in execute
    self.action(context)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 202, in action
    self.quadrangulate)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 272, in do_inset
    model.BevelSelectionInModel(m, amount, pitch, quadrangulate, region, False)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 276, in BevelSelectionInModel
    bevel_amount, bevel_pitch, quadrangulate, as_percent)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 185, in BevelPolyAreaInModel
    off.Build(bevel_amount)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  [Previous line repeated 972 more times]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 518, in Build
    self.inneroffsets = [Offset(pa, newt, self.vspeed)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 334, in __init__
    self.InitFaceSpokes(polyarea.poly)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 373, in InitFaceSpokes
    for i, v in enumerate(face_vertices)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 373, in <listcomp>
    for i, v in enumerate(face_vertices)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 94, in __init__
    ang = Angle(prev, v, next, points)  # in range [0, 180)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\triquad.py", line 1086, in Angle
    n1 = Length2(u)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\triquad.py", line 1054, in Length2
    return hypot(v[0], v[1])
RecursionError: maximum recursion depth exceeded while calling a Python object

location: C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py:201

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 195, in execute
    self.action(context)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 202, in action
    self.quadrangulate)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 272, in do_inset
    model.BevelSelectionInModel(m, amount, pitch, quadrangulate, region, False)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 276, in BevelSelectionInModel
    bevel_amount, bevel_pitch, quadrangulate, as_percent)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 185, in BevelPolyAreaInModel
    off.Build(bevel_amount)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  [Previous line repeated 972 more times]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 518, in Build
    self.inneroffsets = [Offset(pa, newt, self.vspeed)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 334, in __init__
    self.InitFaceSpokes(polyarea.poly)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 373, in InitFaceSpokes
    for i, v in enumerate(face_vertices)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 373, in <listcomp>
    for i, v in enumerate(face_vertices)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 94, in __init__
    ang = Angle(prev, v, next, points)  # in range [0, 180)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\triquad.py", line 1086, in Angle
    n1 = Length2(u)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\triquad.py", line 1054, in Length2
    return hypot(v[0], v[1])
RecursionError: maximum recursion depth exceeded while calling a Python object

location: C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py:201

location: C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py:201
Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 195, in execute
    self.action(context)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 202, in action
    self.quadrangulate)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 272, in do_inset
    model.BevelSelectionInModel(m, amount, pitch, quadrangulate, region, False)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 276, in BevelSelectionInModel
    bevel_amount, bevel_pitch, quadrangulate, as_percent)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 185, in BevelPolyAreaInModel
    off.Build(bevel_amount)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttaTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\landscapelab-dev\landscapelab-server\buildings\create_buildings.py", line 673, in <module>
    main(arg)
  File "C:\landscapelab-dev\landscapelab-server\buildings\create_buildings.py", line 664, in main
    create_building(name, vertices, height, textures)
  File "C:\landscapelab-dev\landscapelab-server\buildings\create_buildings.py", line 102, in create_building
    roof = create_roof(name, vertices, height, textures)
  File "C:\landscapelab-dev\landscapelab-server\buildings\create_buildings.py", line 180, in create_roof
    hip_roof(roof, footprint, bm, mesh, roof_height, height, bbox, name, vertices)
  File "C:\landscapelab-dev\landscapelab-server\buildings\create_buildings.py", line 280, in hip_roof
    bpy.ops.mesh.insetstraightskeleton(inset_amount=roof_inset_amount, inset_height=-roof_height, region=True, quadrangulate=True)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 195, in execute
    self.action(context)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 202, in action
    self.quadrangulate)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\__init__.py", line 272, in do_inset
    model.BevelSelectionInModel(m, amount, pitch, quadrangulate, region, False)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 276, in BevelSelectionInModel
    bevel_amount, bevel_pitch, quadrangulate, as_percent)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\model.py", line 185, in BevelPolyAreaInModel
    off.Build(bevel_amount)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 523, in Build
    o.Build(nexttarget)
  [Previous line repeated 972 more times]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 518, in Build
    self.inneroffsets = [Offset(pa, newt, self.vspeed)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 334, in __init__
    self.InitFaceSpokes(polyarea.poly)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 373, in InitFaceSpokes
    for i, v in enumerate(face_vertices)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 373, in <listcomp>
    for i, v in enumerate(face_vertices)]
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\offset.py", line 94, in __init__
    ang = Angle(prev, v, next, points)  # in range [0, 180)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\triquad.py", line 1086, in Angle
    n1 = Length2(u)
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\addons\mesh_inset\triquad.py", line 1054, in Length2
    return hypot(v[0], v[1])
RecursionError: maximum recursion depth exceeded while calling a Python object

location: C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py:201
```

**Comment by chrisgraf** [comment]
we will wait for feedback of the direct building generation in godot but probably will change the building pipeline due to restrictions wihin godot anyhow

**Comment by kb173** [comment]
we have a new system for building generation now
